export enum COLOR_PALETTE {
  GREEN_1 = '#5CA370',
  GREEN_2 = '#9DC8A9',
  GREEN_3 = '#DEEDE2',
  BLUE_1 = '#429ABD',
  BLUE_2 = '#8DC3D8',
  BLUE_3 = '#D9EBF2',
  RED_1 = '#F20D0E',
  RED_2 = '#F76E6F',
  RED_3 = '#FCCFCF',
  ORANGE_1 = '#FF9500',
  ORANGE_2 = '#FFC066',
  ORANGE_3 = '#FFEACC',
  PINK_1 = '#E81778',
  PINK_2 = '#F174AE',
  PINK_3 = '#FAD1E4',
  BLACK_1 = '#1B181B',
  BLACK_2 = '#524752',
  BLACK_3 = '#897689',
  BROWN_1 = '#A97256',
  BROWN_2 = '#CBAA9A',
  BROWN_3 = '#EEE3DD',
  PURPLE_1 = '#9740BF',
  PURPLE_2 = '#C18CD9',
  PURPLE_3 = '#EAD9F2',
  GREY_1 = '#595959',
  GREY_2 = '#909090',
  GREY_3 = '#E9E9E9',
}

export const font_color = {
  GREEN_1: { color: COLOR_PALETTE.GREEN_1 },
  GREEN_2: { color: COLOR_PALETTE.GREEN_2 },
  GREEN_3: { color: COLOR_PALETTE.GREEN_3 },
  BLUE_1: { color: COLOR_PALETTE.BLUE_1 },
  BLUE_2: { color: COLOR_PALETTE.BLUE_2 },
  BLUE_3: { color: COLOR_PALETTE.BLUE_3 },
  RED_1: { color: COLOR_PALETTE.RED_1 },
  RED_2: { color: COLOR_PALETTE.RED_2 },
  RED_3: { color: COLOR_PALETTE.RED_3 },
  ORANGE_1: { color: COLOR_PALETTE.ORANGE_1 },
  ORANGE_2: { color: COLOR_PALETTE.ORANGE_2 },
  ORANGE_3: { color: COLOR_PALETTE.ORANGE_3 },
  PINK_1: { color: COLOR_PALETTE.PINK_1 },
  PINK_2: { color: COLOR_PALETTE.PINK_2 },
  PINK_3: { color: COLOR_PALETTE.PINK_3 },
  BLACK_1: { color: COLOR_PALETTE.BLACK_1 },
  BLACK_2: { color: COLOR_PALETTE.BLACK_2 },
  BLACK_3: { color: COLOR_PALETTE.BLACK_3 },
  BROWN_1: { color: COLOR_PALETTE.BROWN_1 },
  BROWN_2: { color: COLOR_PALETTE.BROWN_2 },
  BROWN_3: { color: COLOR_PALETTE.BROWN_3 },
  PURPLE_1: { color: COLOR_PALETTE.PURPLE_1 },
  PURPLE_2: { color: COLOR_PALETTE.PURPLE_2 },
  PURPLE_3: { color: COLOR_PALETTE.PURPLE_3 },
  GREY_1: { color: COLOR_PALETTE.GREY_1 },
  GREY_2: { color: COLOR_PALETTE.GREY_2 },
  GREY_3: { color: COLOR_PALETTE.GREY_3 },
};

export const font_size = {
  XL: '21px',
  L: '18px',
  M: '16px',
  S: '14px',
  XS: '12px',
  XXS: '11px',
};

export const font_leading = {
  XL: '28px',
  L: '24px',
  M: '20px',
  S: '16px',
};
